ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calon_siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.siswa_aktif ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mutasi_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.informasi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.landing_page_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ui_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;
