import { z } from 'zod';

export const registerApplicantSchema = z.object({
  nama: z.string().optional().or(z.literal('')),
  nisn: z.string().optional().or(z.literal('')),
  nik: z.string().optional().or(z.literal('')),
  tempatLahir: z.string().optional().or(z.literal('')),
  tglLahir: z.string().optional().or(z.literal('')),
  jenisKelamin: z.string().optional().or(z.literal('')),
  agama: z.string().optional().default('Islam'),
  kewarganegaraan: z.string().optional().default('WNI'),
  alamat: z.string().optional().or(z.literal('')),
  rtRw: z.string().optional().default(''),
  kelurahan: z.string().optional().default(''),
  kecamatan: z.string().optional().default(''),
  kodePos: z.string().optional().default(''),
  whatsapp: z.string().optional().or(z.literal('')),
  email: z.string()
    .email('Format email tidak valid.')
    .or(z.literal(''))
    .optional()
    .default(''),
  tinggalDengan: z.string().optional().default('Orang Tua'),
  transportasi: z.string().optional().default('Jalan Kaki'),
  tinggiBadan: z.union([z.number(), z.string()]).optional().default(0),
  beratBadan: z.union([z.number(), z.string()]).optional().default(0),
  jarakSekolah: z.string().optional().default('Kurang dari 1 km'),
  jarakKm: z.union([z.number(), z.string()]).optional().default(0),
  waktuJam: z.union([z.number(), z.string()]).optional().default(0),
  waktuMenit: z.union([z.number(), z.string()]).optional().default(0),
  jumlahSaudara: z.union([z.number(), z.string()]).optional().default(0),
  golonganDarah: z.string().optional().default('O'),
  penyakitDiderita: z.string().optional().default('-'),
  kebutuhanKhusus: z.array(z.string()).optional().default([]),
  jenisPrestasi: z.array(z.string()).optional().default([]),
  tingkatPrestasi: z.array(z.string()).optional().default([]),
  uraianPrestasi: z.string().optional().default(''),
  tahunPrestasi: z.string().optional().default(''),
  penyelenggara: z.string().optional().default(''),
  jenisBeasiswa: z.array(z.string()).optional().default([]),
  uraianBeasiswa: z.string().optional().default(''),
  tahunMulaiBeasiswa: z.string().optional().default(''),
  tahunSelesaiBeasiswa: z.string().optional().default(''),
  namaAyah: z.string().optional().default(''),
  tempatLahirAyah: z.string().optional().default(''),
  tglLahirAyah: z.string().optional().nullable(),
  agamaAyah: z.string().optional().default(''),
  kewarganegaraanAyah: z.string().optional().default('WNI'),
  pendidikanAyah: z.string().optional().default(''),
  pekerjaanAyah: z.string().optional().default(''),
  penghasilanAyah: z.string().optional().default(''),
  alamatAyah: z.string().optional().default(''),
  rtrwAyah: z.string().optional().default(''),
  kelurahanAyah: z.string().optional().default(''),
  kecamatanAyah: z.string().optional().default(''),
  kodePosAyah: z.string().optional().default(''),
  statusAyah: z.string().optional().default('Masih Hidup'),
  namaIbu: z.string().optional().default(''),
  tempatLahirIbu: z.string().optional().default(''),
  tglLahirIbu: z.string().optional().nullable(),
  agamaIbu: z.string().optional().default(''),
  kewarganegaraanIbu: z.string().optional().default('WNI'),
  pendidikanIbu: z.string().optional().default(''),
  pekerjaanIbu: z.string().optional().default(''),
  penghasilanIbu: z.string().optional().default(''),
  alamatIbu: z.string().optional().default(''),
  rtrwIbu: z.string().optional().default(''),
  kelurahanIbu: z.string().optional().default(''),
  kecamatanIbu: z.string().optional().default(''),
  kodePosIbu: z.string().optional().default(''),
  statusIbu: z.string().optional().default('Masih Hidup'),
  namaWali: z.string().optional().default(''),
  tempatLahirWali: z.string().optional().default(''),
  tglLahirWali: z.string().optional().nullable(),
  agamaWali: z.string().optional().default(''),
  kewarganegaraanWali: z.string().optional().default('WNI'),
  pendidikanWali: z.string().optional().default(''),
  pekerjaanWali: z.string().optional().default(''),
  penghasilanWali: z.string().optional().default(''),
  alamatWali: z.string().optional().default(''),
  rtrwWali: z.string().optional().default(''),
  kelurahanWali: z.string().optional().default(''),
  kecamatanWali: z.string().optional().default(''),
  kodePosWali: z.string().optional().default(''),
  statusWali: z.string().optional().default('Masih Hidup'),
  teleponOrtu: z.string().optional().default(''),
  sekolahAsal: z.string().optional().or(z.literal('')),
  tglLulus: z.string().optional().nullable(),
  noIjazah: z.string().optional().default(''),
  noSKHUN: z.string().optional().default(''),
  noPesertaUN: z.string().optional().default(''),
  lamaBelajar: z.union([z.number(), z.string()]).optional().default(3),
  pindahanDari: z.string().optional().default(''),
  alasanPindah: z.string().optional().default(''),
  diterimaKelas: z.string().optional().nullable(),
  diterima_kelas: z.string().optional().nullable(),
  diterimaTanggal: z.string().optional().nullable(),
  diterima_tanggal: z.string().optional().nullable(),
  jurusan1: z.string().optional().or(z.literal('')),
  hobi: z.array(z.string()).optional().default([]),
  citaCita: z.string().optional().default(''),
  nilaiUSTeori: z.union([z.number(), z.string()]).optional().default(0),
  nilaiUSPraktik: z.union([z.number(), z.string()]).optional().default(0),
  nilaiMuatanLokal: z.union([z.number(), z.string()]).optional().default(0),
  alasanMemilih: z.string().optional().default(''),
  citaCitaSetelahLulus: z.string().optional().default(''),
  pelajaranDisenangi: z.string().optional().default(''),
  punyaKPS: z.string().optional().default('Tidak'),
  noKPS: z.string().optional().default(''),
  punyaKIP: z.string().optional().default('Tidak'),
  noKIP: z.string().optional().default(''),
  alasanDisenangi: z.string().optional().default(''),
  kesulitanBelajar: z.string().optional().default(''),
  perkelahian: z.string().optional().default(''),
  ketPerkelahian: z.string().optional().default(''),
  narkoba: z.string().optional().default(''),
  ketNarkoba: z.string().optional().default(''),
  pelanggaranLain: z.string().optional().default(''),
  ketPelanggaranLain: z.string().optional().default(''),
  janjiTaat: z.union([z.boolean(), z.string()]).optional(),
  janjiSanksi: z.union([z.boolean(), z.string()]).optional(),
  janjiAkrab: z.union([z.boolean(), z.string()]).optional(),
  janjiBelajar: z.union([z.boolean(), z.string()]).optional(),
  janjiNamaBaik: z.union([z.boolean(), z.string()]).optional(),
  periode: z.string().optional().default('2026-2027'),
});

export const updateApplicantSchema = registerApplicantSchema.partial().passthrough();
